### ISSUE TITLE
[BUG] `hasComma` does not format number with decimals correctly 

### ISSUE THREAD

**Issue by carlosfebres** [eunvanz/react-awesome-animated-number#2]
The following image shows the bug, `hasComma` is true and the number has decimals

![image](https://github.com/eunvanz/react-awesome-animated-number/assets/2939980/bb4e9447-dead-4a0c-9f73-d9d27736ebec)

**Comment by eunvanz** [comment]
It's fixed in v.1.0.13 and it's available now. thx!

**Comment by carlosfebres** [comment]
Thanks @eunvanz !!
